[package]
name = "anylist_client"
version = "0.1.0"
authors = ["Phil Denhoff <phil@denhoff.ca>"]
edition = "2021"
include = ["src/"]

[lib]
name = "anylist_client"
crate-type = ["lib", "cdylib"]
bench = false
path = "src/lib.rs"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0"
serde_derive = "1.0"
tokio = { version = "1", features = ["full"] }
prost = "0.12"

[build-dependencies]
prost-build = "0.11.0"